# Generated by Django 3.0.8 on 2020-08-13 18:37

import bug_tracker_v2.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200812_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and ./+/-/_ only.', max_length=150, unique=True, validators=[bug_tracker_v2.users.models.MyUnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
